import { APIGateway } from "./apigateway";
import { CloudWatch } from "./cloudwatch";
import { DynamoDB } from "./dynamodb";
import { EC2 } from "./ec2";
import { ECR } from "./ecr";
import { ECS } from "./ecs";
import { Events } from "./events";
import { IAM } from "./iam";
import { KMS } from "./kms";
import { Lambda } from "./lambda";
import { Logs } from "./logs";
import { Route53 } from "./route53";
import { S3 } from "./s3";
import { SQS } from "./sqs";
export declare class AWS {
    static APIGateway: typeof APIGateway;
    static CloudWatch: typeof CloudWatch;
    static DynamoDB: typeof DynamoDB;
    static EC2: typeof EC2;
    static ECR: typeof ECR;
    static ECS: typeof ECS;
    static Events: typeof Events;
    static IAM: typeof IAM;
    static KMS: typeof KMS;
    static Lambda: typeof Lambda;
    static Logs: typeof Logs;
    static Route53: typeof Route53;
    static S3: typeof S3;
    static SQS: typeof SQS;
}
