export class APIGateway {
  static Account = "AWS::APIGateway::Account";
  static ApiKey = "AWS::APIGateway::ApiKey";
  static Authorizer = "AWS::APIGateway::Authorizer";
  static BasePathMapping = "AWS::APIGateway::BasePathMapping";
  static ClientCertificate = "AWS::APIGateway::ClientCertificate";
  static Deployment = "AWS::APIGateway::Deployment";
  static DocumentationPart = "AWS::APIGateway::DocumentationPart";
  static DocumentationVersion = "AWS::APIGateway::DocumentationVersion";
  static DomainName = "AWS::APIGateway::DomainName";
  static GatewayResponse = "AWS::APIGateway::GatewayResponse";
  static Method = "AWS::APIGateway::Method";
  static Model = "AWS::APIGateway::Model";
  static RequestValidator = "AWS::APIGateway::RequestValidator";
  static Resource = "AWS::APIGateway::Resource";
  static RestApi = "AWS::APIGateway::RestApi";
  static Stage = "AWS::APIGateway::Stage";
  static UsagePlan = "AWS::APIGateway::UsagePlan";
  static UsagePlanKey = "AWS::APIGateway::UsagePlanKey";
  static VpcLink = "AWS::APIGateway::VpcLink";
}
