export class ApiGateway {
  static Account = "AWS::ApiGateway::Account";
  static ApiKey = "AWS::ApiGateway::ApiKey";
  static Authorizer = "AWS::ApiGateway::Authorizer";
  static BasePathMapping = "AWS::ApiGateway::BasePathMapping";
  static ClientCertificate = "AWS::ApiGateway::ClientCertificate";
  static Deployment = "AWS::ApiGateway::Deployment";
  static DocumentationPart = "AWS::ApiGateway::DocumentationPart";
  static DocumentationVersion = "AWS::ApiGateway::DocumentationVersion";
  static DomainName = "AWS::ApiGateway::DomainName";
  static GatewayResponse = "AWS::ApiGateway::GatewayResponse";
  static Method = "AWS::ApiGateway::Method";
  static Model = "AWS::ApiGateway::Model";
  static RequestValidator = "AWS::ApiGateway::RequestValidator";
  static Resource = "AWS::ApiGateway::Resource";
  static RestApi = "AWS::ApiGateway::RestApi";
  static Stage = "AWS::ApiGateway::Stage";
  static UsagePlan = "AWS::ApiGateway::UsagePlan";
  static UsagePlanKey = "AWS::ApiGateway::UsagePlanKey";
  static VpcLink = "AWS::ApiGateway::VpcLink";
}
