export class IAM {
  static AccessKey = 'AWS::IAM::AccessKey'
  static Group = 'AWS::IAM::Group'
  static InstanceProfile = 'AWS::IAM::InstanceProfile'
  static ManagedPolicy = 'AWS::IAM::ManagedPolicy'
  static OIDCProvider = 'AWS::IAM::OIDCProvider'
  static Policy = 'AWS::IAM::Policy'
  static Role = 'AWS::IAM::Role'
  static SAMLProvider = 'AWS::IAM::SAMLProvider'
  static ServerCertificate = 'AWS::IAM::ServerCertificate'
  static ServiceLinkedRole = 'AWS::IAM::ServiceLinkedRole'
  static User = 'AWS::IAM::User'
  static UserToGroupAddition = 'AWS::IAM::UserToGroupAddition'
  static VirtualMFADevice = 'AWS::IAM::VirtualMFADevice'
}